#!/usr/bin/env bash
# Generated by the github-macos-app-release Codex skill.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/ziward-inc/fig-wizard/main/install.sh | bash
#   wget -qO- https://raw.githubusercontent.com/ziward-inc/fig-wizard/main/install.sh | bash
set -euo pipefail

REPO='ziward-inc/fig-wizard'
APP_NAME='FigWizard'
APP_BUNDLE="${APP_NAME}.app"
INSTALL_DIR='/Applications'
SUPPORTED_ARCH='arm64'
MIN_MACOS='15+'
DMG_SUFFIX='_aarch64.dmg'

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: ${APP_NAME} only supports macOS." >&2
  exit 1
fi
if [[ "$SUPPORTED_ARCH" != "any" && "$(uname -m)" != "$SUPPORTED_ARCH" ]]; then
  echo "error: ${APP_NAME} requires ${SUPPORTED_ARCH} (macOS ${MIN_MACOS})." >&2
  exit 1
fi
if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
  echo "error: curl or wget is required." >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
  echo "error: jq or python3 is required to read GitHub Release metadata." >&2
  exit 1
fi

api_get() { # $1 = URL
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL -H "Accept: application/vnd.github+json" "$1"
  else
    wget -qO- --header="Accept: application/vnd.github+json" "$1"
  fi
}

download_asset() { # $1 = download URL, $2 = output path
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL -L -o "$2" "$1"
  else
    wget -qO "$2" "$1"
  fi
}

release_field() { # $1 = release JSON, $2 = field name
  if command -v jq >/dev/null 2>&1; then
    if [[ "$2" == "tag_name" ]]; then
      printf '%s' "$1" | jq -r '.tag_name // empty'
    else
      printf '%s' "$1" | jq -r --arg field "$2" --arg suffix "$DMG_SUFFIX" \
        '[.assets[] | select(.name | endswith($suffix))][0][$field] // empty'
    fi
  else
    FIELD="$2" DMG_SUFFIX="$DMG_SUFFIX" python3 -c '
import json, os, sys
data = json.load(sys.stdin)
field = os.environ["FIELD"]
suffix = os.environ["DMG_SUFFIX"]
if field == "tag_name":
    print(data.get("tag_name", ""))
else:
    for asset in data.get("assets", []):
        if asset.get("name", "").endswith(suffix):
            print(asset.get(field, ""))
            break
' <<<"$1"
  fi
}

echo "==> Looking up the latest ${APP_NAME} release..."
RELEASE_JSON="$(api_get "https://api.github.com/repos/${REPO}/releases/latest")"
TAG="$(release_field "$RELEASE_JSON" tag_name)"
ASSET_URL="$(release_field "$RELEASE_JSON" browser_download_url)"
ASSET_NAME="$(release_field "$RELEASE_JSON" name)"

if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: latest Release tag is not vA.B.C: ${TAG:-<empty>}" >&2
  exit 1
fi
if [[ -z "$ASSET_URL" || -z "$ASSET_NAME" ]]; then
  echo "error: no Release asset ending in ${DMG_SUFFIX} was found on ${TAG}." >&2
  exit 1
fi

echo "==> Found ${ASSET_NAME} (${TAG})"

INSTALLED_APP="${INSTALL_DIR}/${APP_BUNDLE}"
INSTALLED_INFO="${INSTALLED_APP}/Contents/Info.plist"
if [[ -f "$INSTALLED_INFO" ]]; then
  INSTALLED_VERSION="$(plutil -extract CFBundleShortVersionString raw "$INSTALLED_INFO" 2>/dev/null || true)"
  if [[ -n "$INSTALLED_VERSION" && "$INSTALLED_VERSION" == "${TAG#v}" ]]; then
    if [[ ! -t 1 ]]; then
      echo "error: ${APP_NAME} ${TAG} is already installed. Re-run from an interactive terminal to confirm overwrite." >&2
      exit 1
    fi

    printf "%s %s is already installed. Overwrite and reinstall? [y/N] " "$APP_NAME" "$TAG" >/dev/tty
    IFS= read -r OVERWRITE_REPLY </dev/tty
    case "$OVERWRITE_REPLY" in
      [yY] | [yY][eE][sS])
        echo "==> Reinstalling ${APP_NAME} ${TAG}..."
        ;;
      *)
        echo "==> Installation cancelled."
        exit 0
        ;;
    esac
  elif [[ -n "$INSTALLED_VERSION" ]]; then
    echo "==> Installed ${INSTALLED_VERSION} differs from latest ${TAG#v}; updating..."
  fi
fi

WORKDIR=""
MOUNT_POINT=""
MOUNTED=0
cleanup() {
  if [[ "$MOUNTED" == "1" && -n "$MOUNT_POINT" ]]; then
    hdiutil detach "$MOUNT_POINT" -quiet >/dev/null 2>&1 || true
  fi
  if [[ -n "$WORKDIR" && -d "$WORKDIR" ]]; then
    rm -rf "$WORKDIR"
  fi
}
trap cleanup EXIT

WORKDIR="$(mktemp -d)"
DMG_PATH="${WORKDIR}/${ASSET_NAME}"
MOUNT_POINT="${WORKDIR}/mount"
mkdir "$MOUNT_POINT"

echo "==> Downloading ${ASSET_NAME}..."
download_asset "$ASSET_URL" "$DMG_PATH"

echo "==> Mounting disk image..."
hdiutil attach "$DMG_PATH" -nobrowse -readonly -quiet -mountpoint "$MOUNT_POINT"
MOUNTED=1

SOURCE_APP="${MOUNT_POINT}/${APP_BUNDLE}"
if [[ ! -d "$SOURCE_APP" ]]; then
  echo "error: ${APP_BUNDLE} was not found inside ${ASSET_NAME}." >&2
  exit 1
fi
if [[ ! -d "$INSTALL_DIR" ]]; then
  echo "error: install directory does not exist: ${INSTALL_DIR}" >&2
  exit 1
fi

echo "==> Installing ${APP_BUNDLE} to ${INSTALL_DIR}..."
rm -rf "$INSTALLED_APP"
cp -R "$SOURCE_APP" "$INSTALLED_APP"

hdiutil detach "$MOUNT_POINT" -quiet
MOUNTED=0

xattr -cr "$INSTALLED_APP"

echo "==> Launching ${APP_BUNDLE}..."
open "$INSTALLED_APP"

echo ""
echo "${APP_NAME} (${TAG}) installed and launched from ${INSTALLED_APP}"
